/** 테이블 삭제문 **/
/*참조 역순으로 삭제 해야함*/

DROP TABLE POLICY_TB;
DROP TABLE POINT_TB;
DROP TABLE PAGE_CONNECTION_TB;
DROP TABLE NOTICE_TB;
DROP TABLE MANAGER_TB;
DROP TABLE ANSWER_TB;
DROP TABLE RETURN_TB;
DROP TABLE QUESTION_TB;
DROP TABLE REVIEW_TB;
DROP TABLE ORDER_DETAIL_TB;
DROP TABLE ORDER_TB;
DROP TABLE STOCK_TB;
DROP TABLE RM_PCT_TB;
DROP TABLE RAWMATERIAL_TB;
DROP TABLE CART_TB;
DROP TABLE USER_TB;
DROP TABLE PRODUCT_MST_TB;